class ExceptionTest1{
	public static void main(String[] a){
	int j=231;
	long b=432;
	try{
	long l=j/b;
	System.out.println("a value");
	}
	catch(Exception k){
	System.out.println("b value");
	}
	}
}