class Exception4{
	public static void main(String...a){
	int l=134;
	int b=0;
	try{
	int c=l/b;
	System.out.println("c");
	}
	catch(Exception r){
	System.out.println("value");
	}
	}
}